### ISSUE TITLE
ItemsExtractor doesn't work on Linux

### ISSUE THREAD

**Issue by Nadyita** [Budabot/ItemsExtractor#1]
When using release 1.4 on Linux, I get the following stacktrace:

```
# java -cp ".:lib/*" com.jkbff.ao.itemsextractor.Program -d /home/mark/Games/AOClassic/drive_c/Funcom/Anarchy\ Online/
2018-10-18 23:34:49,287 DEBUG [main] (Runner.scala:30) - reading index file entries
2018-10-18 23:34:58,226 ERROR [main] (Program.scala:24) -
java.io.EOFException
        at java.io.RandomAccessFile.readFully(RandomAccessFile.java:438)
        at java.io.RandomAccessFile.readFully(RandomAccessFile.java:416)
        at com.jkbff.ao.itemsextractor.rdb.RDBFunctions$.readLittleEndianInt(RDBFunctions.scala:13)
        at com.jkbff.ao.itemsextractor.rdb.RDBExtractor.parseAttribute(RDBExtractor.scala:45)
        at com.jkbff.ao.itemsextractor.rdb.RDBExtractor$$anonfun$1.apply(RDBExtractor.scala:20)
        at com.jkbff.ao.itemsextractor.rdb.RDBExtractor$$anonfun$1.apply(RDBExtractor.scala:20)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:142)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:142)
        at scala.collection.immutable.NumericRange.foreach(NumericRange.scala:73)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:142)
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
        at com.jkbff.ao.itemsextractor.rdb.RDBExtractor.readItem(RDBExtractor.scala:20)
        at com.jkbff.ao.itemsextractor.Runner$$anonfun$1.apply(Runner.scala:31)
        at com.jkbff.ao.itemsextractor.Runner$$anonfun$1.apply(Runner.scala:31)
        at scala.collection.immutable.List.map(List.scala:277)
        at com.jkbff.ao.itemsextractor.Runner.getEntries(Runner.scala:31)
        at com.jkbff.ao.itemsextractor.Runner.run(Runner.scala:26)
        at com.jkbff.ao.itemsextractor.Program$.delayedEndpoint$com$jkbff$ao$itemsextractor$Program$1(Program.scala:27)
        at com.jkbff.ao.itemsextractor.Program$delayedInit$body.apply(Program.scala:9)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at com.jkbff.ao.itemsextractor.Program$.main(Program.scala:9)
        at com.jkbff.ao.itemsextractor.Program.main(Program.scala)
```

As I have no clue about Scala, there isn't much debugging I can contribute.

**Comment by bigwheels16** [comment]
I tried this on linux as well and I got the same error.  But I don't know what the problem is...

**Comment by Nadyita** [comment]
Another release and stikll the same error. More debug output though it seems:

```
2019-10-17 11:42:29,696 DEBUG [main] (BudabotSqlDumpModule.scala:26) - reading index file entries
record IndexRecord(1000020,257705,2184585765)
Breaking for setType 120358584
Total bytes: 3302222423
Remaining bytes: 3278630455
Last setType: -1
2019-10-17 11:42:48,879 ERROR [main] (Program.scala:28) -
java.io.EOFException
	at java.io.RandomAccessFile.readFully(RandomAccessFile.java:438)
	at java.io.RandomAccessFile.readFully(RandomAccessFile.java:416)
	at com.jkbff.ao.itemsextractor.rdb.RDBFunctions$.readLittleEndianInt(RDBFunctions.scala:13)
	at com.jkbff.ao.itemsextractor.rdb.RDBExtractor.consumeRemainingBytes(RDBExtractor.scala:112)
	at com.jkbff.ao.itemsextractor.rdb.RDBExtractor$$anonfun$readItem$1.apply$mcV$sp(RDBExtractor.scala:101)
	at scala.util.control.Breaks.breakable(Breaks.scala:38)
	at com.jkbff.ao.itemsextractor.rdb.RDBExtractor.readItem(RDBExtractor.scala:39)
	at com.jkbff.ao.itemsextractor.BudabotSqlDumpModule$$anonfun$2.apply(BudabotSqlDumpModule.scala:27)
	at com.jkbff.ao.itemsextractor.BudabotSqlDumpModule$$anonfun$2.apply(BudabotSqlDumpModule.scala:27)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.immutable.List.map(List.scala:285)
	at com.jkbff.ao.itemsextractor.BudabotSqlDumpModule.getEntries(BudabotSqlDumpModule.scala:27)
	at com.jkbff.ao.itemsextractor.BudabotSqlDumpModule.execute(BudabotSqlDumpModule.scala:16)
	at com.jkbff.ao.itemsextractor.Program$$anonfun$1.apply(Program.scala:34)
	at com.jkbff.ao.itemsextractor.Program$$anonfun$1.apply(Program.scala:31)
	at com.jkbff.common.Helper$.using(Helper.scala:22)
	at com.jkbff.ao.itemsextractor.Program$.delayedEndpoint$com$jkbff$ao$itemsextractor$Program$1(Program.scala:31)
	at com.jkbff.ao.itemsextractor.Program$delayedInit$body.apply(Program.scala:12)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.jkbff.ao.itemsextractor.Program$.main(Program.scala:12)
	at com.jkbff.ao.itemsextractor.Program.main(Program.scala)
```

Did you get any clue as to how to fix this?

**Comment by bigwheels16** [comment]
I still don't know how to fix this...

**Comment by bigwheels16** [comment]
this should now work on linux
